version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    command: serve

  backend:
    build:
      context: ./backend
    image: sre-genai-backend
    container_name: sre-genai-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama

  frontend:
    build:
      context: ./frontend
    image: sre-genai-frontend
    container_name: sre-genai-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  ollama_data:
